esphome:
  name: boilerctrl
  friendly_name: boilerctrl

logger:
  level: DEBUG

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

mqtt:
  broker: !secret mqtt_broker

#api:

ota:
  platform: esphome




output:
  - platform: gpio
    pin: GPIO23
    id: led
  - platform: gpio
    pin: GPIO32
    id: relay_pin_1
  - platform: gpio
    pin: GPIO33
    id: relay_pin_2
  - platform: gpio
    pin: GPIO25
    id: relay_pin_3
  - platform: gpio
    pin: GPIO26
    id: relay_pin_4

# Define the switches based on the relay pins
switch:
  - platform: output
    id: zone_1
    name: "Zone 1"
    output: relay_pin_1
  - platform: output
    id: zone_2
    name: "Zone 2"
    output: relay_pin_2
  - platform: output
    id: zone_3
    name: "Zone 3"
    output: relay_pin_3
  - platform: output
    id: zone_4
    name: "Zone 4"
    output: relay_pin_4

interval:
  - interval: 1000ms
    then:
      - output.turn_on: led
      - delay: 500ms
      - output.turn_off: led

one_wire:
  - platform: gpio
    pin: GPIO27


sensor:
  - platform: dallas_temp
    address: 0xcf4b39d4457ae128
    name: "TH01"
  - platform: dallas_temp
    address: 0x427138d445492528
    name: "TH02"
  - platform: dallas_temp
    address: 0xe40dbdd44534c228
    name: "TH03"
  - platform: dallas_temp
    address: 0x92638ad4451db628 
    name: "TH04"
  - platform: dallas_temp
    address: 0xbd70fcd445345428
    name: "TH05"
  - platform: dallas_temp
    address: 0x271f24d445e87728
    name: "TH_DHW"

