#
#  Boiler Controller ESPHome Configuration
#  This is intended for a 4 channel ESP32 based relay board.
#  See https://github.com/jones139/HomeAutomation/tree/main/Heating_Controller for more details.
#
#  Graham Jones, 2024
#
#


esphome:
  name: boilerctrl
  friendly_name: boilerctrl

logger:
  level: DEBUG

esp32:
  board: esp32dev
  framework:
    type: arduino

# Configure the wifi network for us to connect to
wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_passwd
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_passwd

# Define the host name or IP address of the MQTT broker to use.
mqtt:
  broker: !secret mqtt_broker

# We are not using the ESPHome API - we are using MQTT instead, so API is commented out.
#api:

# Enable Over the Air updates.
ota:
  platform: esphome
  password: !secret ota_passwd


# Define which GPI is used for which output channel.
output:
  - platform: gpio
    pin: GPIO23
    id: led
  - platform: gpio
    pin: GPIO32
    id: relay_pin_1
  - platform: gpio
    pin: GPIO33
    id: relay_pin_2
  - platform: gpio
    pin: GPIO25
    id: relay_pin_3
  - platform: gpio
    pin: GPIO26
    id: relay_pin_4

# Define the switches based on the relay pins
switch:
  - platform: output
    id: zone_1
    name: "Zone 1"
    output: relay_pin_1
  - platform: output
    id: zone_2
    name: "Zone 2"
    output: relay_pin_2
  - platform: output
    id: zone_3
    name: "Zone 3"
    output: relay_pin_3
  - platform: output
    id: zone_4
    name: "Zone 4"
    output: relay_pin_4

# We flash the on-board LED so we know the firmware is alive.
interval:
  - interval: 2000ms
    then:
      - output.turn_on: led
      - delay: 1000ms
      - output.turn_off: led


#
# Enable the optional temperature monitoring system - a 1 wire bus connected to GPIO27
#
one_wire:
  - platform: gpio
    pin: GPIO27

# Note, the device addresses will need to be updated for a new system.
sensor:
  - platform: dallas_temp
    address: 0xcf4b39d4457ae128
    name: "TH01"
  - platform: dallas_temp
    address: 0x427138d445492528
    name: "TH02"
  - platform: dallas_temp
    address: 0xe40dbdd44534c228
    name: "TH03"
  - platform: dallas_temp
    address: 0x92638ad4451db628 
    name: "TH04"
  - platform: dallas_temp
    address: 0xbd70fcd445345428
    name: "TH05"
  - platform: dallas_temp
    address: 0x271f24d445e87728
    name: "TH_DHW"

